title: SIS SQUAD XYI
baseurl: "/Sissquad9.github.io"
url: "https://friiik66699666.github.io"
theme: minima

plugins:
  - jekyll-feed

defaults:
  - scope:
      path: ""
    values:
      layout: "page"
